create table "Hospital" (
	"ID" nvarchar2(5) not null,
	"Title" nvarchar2(30) not null,
	"Address" nVARCHAR2(50) NOT NULL,
	constraint HOSPITAL_PK PRIMARY KEY ("ID"));


/
create table Visit_types (
	ID number generated by default as identity(start with 1 increment by 1),
	type nvarchar2(20) not null,
	constraint VISIT_TYPEs_PK PRIMARY KEY ("ID"));

/
create table "Doctor_category" (
	"ID" nvarchar2(1) not null,
	"Category" nVARCHAR2(15) NOT NULL,
	constraint DOCTOR_CATEGORY_PK PRIMARY KEY ("ID"));


/
CREATE TABLE Doctor_specializations (
	ID number generated by default as identity(start with 1 increment by 1),
	specialization nvarchar2(25) not null,
	constraint DOCTOR_SPECIALIZATIONs_PK PRIMARY KEY (ID));



/
create table doctors (
	ID number generated by default as identity(start with 1 increment by 1),
	Name nvarchar2(30) not null,
	Address nvarchar2(30) not null,
	Phone nvarchar2(20) not null,
	Category nVARCHAR2(1) NOT NULL,
	Specialization INT NOT NULL,
	Salary decimal not null,
	Hospital nVARCHAR2(5) NOT NULL,
	constraint DOCTORs_PK PRIMARY KEY (ID));


/
CREATE TABLE Users (
	ID number generated by default as identity(start with 1 increment by 1),
	Login nvarchar2(20) not null,
	Password nVARCHAR2(50) NOT NULL,
	DoctorID INT ,
	paientid int ,
	constraint USERs_PK PRIMARY KEY (ID));

/
create table "Room_type" (
	"ID" nvarchar2(3) not null,
	"Type" nVARCHAR2(20) NOT NULL,
	constraint ROOM_TYPE_PK PRIMARY KEY ("ID"));


/
create table rooms (
  Room_number nvarchar2(10) not null,
	type nvarchar2(10) not null,
	constraint ROOMs_PK PRIMARY KEY ( Room_number));


/
CREATE TABLE Patients (
	ID number generated by default as identity(start with 1 increment by 1),
	name nVARCHAR2(30) NOT NULL,
	Birthdate date not null,
	Address nvarchar2(50) not null,
	Phone nVARCHAR2(20) NOT NULL,
	constraint PATIENTs_PK PRIMARY KEY (ID));


/
CREATE TABLE Visits (
	Doctor INT NOT NULL,
	Patient int not null,
	DateTime DATE NOT NULL,
	Type int not null,
	Sympthoms nvarchar2(200),
	Diagnosis nvarchar2(200),
	Prescription nvarchar2(200),
	Notes nvarchar2(200),
	room nvarchar2(10) not null,
	constraint VISIT_PK PRIMARY KEY (Doctor,DateTime, Room));

/




alter table doctors add constraint doctors_fk0 foreign key (category) references doctor_categories(id);
ALTER TABLE Doctors ADD CONSTRAINT Doctors_fk1 FOREIGN KEY (Specialization) REFERENCES Doctor_specializations(ID);

alter table users add constraint users_fk0 foreign key (doctorid) references doctors(id);
ALTER TABLE Users ADD CONSTRAINT Users_fk1 FOREIGN KEY (PaientID) REFERENCES Patients(ID);

ALTER TABLE Rooms ADD CONSTRAINT Rooms_fk1 FOREIGN KEY (Type) REFERENCES Room_types(ID);


ALTER TABLE Visits ADD CONSTRAINT Visits_fk0 FOREIGN KEY (Doctor) REFERENCES Doctors(ID);
alter table visits add constraint visits_fk1 foreign key (Patient) references Patients(ID);
alter table visits add constraint visits_fk2 foreign key (type) references visit_types(id);
ALTER TABLE Visits ADD CONSTRAINT Visits_fk3 FOREIGN KEY (Room) REFERENCES Rooms(ROOM_NUMBER);
